// apps/angular-insurance/src/app/layout/app-shell.ts
// apps/angular-insurance/src/app/layout/app-shell.ts — the insurance app's chrome.
//
// Same structure as the banking shell, deliberately: one platform, and a customer moving between the
// two products should not have to relearn where anything is. What differs is the wordmark and the
// accent on the brand tile — enough to know which product you are in, not enough to feel like a
// different company. That it is written in Angular and banking is written in React is precisely the
// thing a visitor should NOT be able to tell.
//
// A sidebar on wide screens and a slide-over on narrow ones: a nav that stays a hamburger at 1600px
// wastes the space that makes a product feel like a product, and one that stays a fixed sidebar at
// 380px eats the content.
//
// The sidebar is navy rather than brand indigo on purpose. Chrome should recede — a full-height panel
// in the primary action colour makes every menu item compete with the page's actual call to action.
//
// THE KYC BADGE READS FROM THE SHARED RECORD. If someone completed onboarding in the banking app,
// this sidebar shows it as done without the insurance app collecting anything — see
// `app-shell.html`'s header note for the one caveat about which browser origin that holds in.
//
// A PARENT ROUTE, not a wrapper repeated on every screen. The React app spells out
// `<Protected><AppShell>…</AppShell></Protected>` eighteen times; Angular can hang the guard and the
// chrome on one parent and let `<router-outlet>` fill in. Fewer places for one screen to be
// accidentally left unguarded.
import { Component, inject, signal } from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { NavigationEnd, Router, RouterLink, RouterOutlet } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { filter, map } from 'rxjs';
import {
  BadgeCheck,
  FileText,
  HeartPulse,
  LayoutDashboard,
  ListRestart,
  LogOut,
  LucideAngularModule,
  Menu,
  RotateCcw,
  ScrollText,
  ShieldCheck,
  ShieldPlus,
  Users,
  X,
} from 'lucide-angular';
import {
  STEP_SEQUENCE,
  completedCount,
  overallStatus,
  resetAll,
  resetVerification,
} from '@finsecure/shared/core';
import { AuthService } from '../core/auth.service';

@Component({
  selector: 'app-shell',
  imports: [RouterLink, RouterOutlet, LucideAngularModule, NgTemplateOutlet],
  templateUrl: './app-shell.html',
})
export class AppShell {
  private readonly router = inject(Router);
  readonly auth = inject(AuthService);

  readonly drawerOpen = signal(false);
  readonly stepCount = STEP_SEQUENCE.length;

  readonly icons = {
    menu: Menu,
    close: X,
    brand: ShieldPlus,
    signOut: LogOut,
    resetVerification: ListRestart,
    resetAll: RotateCcw,
  };

  /** One icon family, one stroke width, one size token. */
  readonly nav = [
    { label: 'Overview', to: '/dashboard', icon: LayoutDashboard },
    { label: 'Buy a policy', to: '/apply', icon: ShieldPlus },
    { label: 'My policies', to: '/policies', icon: ScrollText },
    { label: 'Claims', to: '/claims', icon: HeartPulse },
    { label: 'KYC status', to: '/kyc', icon: BadgeCheck },
    { label: 'Nominees', to: '/nominees', icon: Users },
    { label: 'Documents', to: '/documents', icon: FileText },
    { label: 'Privacy & consent', to: '/privacy', icon: ShieldCheck },
  ];

  /**
   * The current path, as a signal.
   *
   * Seeded with `router.url` rather than starting empty: the first navigation has already happened by
   * the time this component exists, so a stream of future events alone would leave every nav item
   * unselected until the person clicked something.
   */
  readonly path = toSignal(
    this.router.events.pipe(
      filter((event): event is NavigationEnd => event instanceof NavigationEnd),
      map((event) => event.urlAfterRedirects),
    ),
    { initialValue: this.router.url },
  );

  isActive(to: string): boolean {
    const current = this.path();
    return current === to || current.startsWith(to + '/');
  }

  /** How far through onboarding this customer is — the sidebar's one job beyond navigation is to say
   * there is work waiting, without them opening the page to find out. */
  kycDone(): number {
    const kyc = this.auth.kyc();
    return kyc ? completedCount(kyc) : 0;
  }

  kycVerified(): boolean {
    const kyc = this.auth.kyc();
    return (kyc ? overallStatus(kyc) : 'not_started') === 'verified';
  }

  initials(name: string | undefined): string {
    const parts = (name ?? '').trim().split(/\s+/).filter(Boolean);
    if (parts.length === 0) return '—';
    return (parts[0]![0]! + (parts[1]?.[0] ?? '')).toUpperCase();
  }

  /**
   * Puts every verification step back to not-started, so the onboarding flow can be walked again.
   *
   * A full reload rather than a signal refresh, and deliberately: the person is very likely standing
   * mid-flow on a step that is about to stop existing, and re-entering the router from a clean state
   * is more honest than re-rendering a screen whose data was just deleted underneath it.
   */
  resetVerification(): void {
    const user = this.auth.user();
    if (!user) return;
    resetVerification(user.id);
    this.auth.refresh();
    window.location.reload();
  }

  /** Wipes every store, including the session — so this necessarily lands on the login screen. */
  resetDemoData(): void {
    resetAll();
    window.location.href = '/login';
  }

  signOut(): void {
    this.auth.signOut();
    void this.router.navigate(['/login']);
  }
}

// apps/insurance/src/layout/AppShell.tsx
// apps/insurance/src/layout/AppShell.tsx — the insurance app's chrome.
//
// Same structure as the banking shell, deliberately: one platform, and a customer moving between
// them should not have to relearn where anything is. What differs is the wordmark and the accent on
// the brand tile — enough to know which product you are in, not enough to feel like a different
// company.
//
// The KYC badge here reads from the SHARED record. If someone completed onboarding in the banking
// app, this sidebar shows it as done without the insurance app collecting anything.
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import type { ReactNode } from 'react';
import {
  BadgeCheck,
  FileText,
  HeartPulse,
  LayoutDashboard,
  LogOut,
  Menu,
  RotateCcw,
  ScrollText,
  ShieldCheck,
  ShieldPlus,
  Users,
  X,
} from 'lucide-react';
import { completedCount, overallStatus, resetAll, STEP_SEQUENCE, useAuth } from '@finsecure/shared';

const NAV = [
  { label: 'Overview', to: '/dashboard', icon: LayoutDashboard },
  { label: 'Buy a policy', to: '/apply', icon: ShieldPlus },
  { label: 'My policies', to: '/policies', icon: ScrollText },
  { label: 'Claims', to: '/claims', icon: HeartPulse },
  { label: 'KYC status', to: '/kyc', icon: BadgeCheck },
  { label: 'Nominees', to: '/nominees', icon: Users },
  { label: 'Documents', to: '/documents', icon: FileText },
  { label: 'Privacy & consent', to: '/privacy', icon: ShieldCheck },
];

export function AppShell({ children }: { children: ReactNode }) {
  const { user, kyc, signOut } = useAuth();
  const location = useLocation();
  const [drawerOpen, setDrawerOpen] = useState(false);

  const kycStatus = kyc ? overallStatus(kyc) : 'not_started';
  const done = kyc ? completedCount(kyc) : 0;

  const nav = (
    <nav className="flex-1 space-y-0.5 px-3 py-4">
      {NAV.map(({ label, to, icon: Icon }) => {
        const active = location.pathname === to || location.pathname.startsWith(to + '/');
        return (
          <Link
            key={to}
            to={to}
            onClick={() => setDrawerOpen(false)}
            aria-current={active ? 'page' : undefined}
            className={
              // `relative` is load-bearing: the active accent bar below is absolutely positioned and
              // would otherwise anchor to the nearest positioned ancestor, landing at the edge of the
              // sidebar instead of beside its own row.
              'focus-ring relative flex min-h-11 items-center gap-3 rounded-control px-3 text-sm transition-colors ' +
              (active
                ? 'bg-white/[0.09] font-semibold text-white shadow-[inset_0_1px_0_0_rgb(255_255_255/0.06)]'
                : 'font-medium text-slate-400 hover:bg-white/[0.05] hover:text-slate-100')
            }
          >
            {/* The accent bar is what makes the selected item read as selected at a glance,
                without relying on the background tint alone. */}
            {active && (
              <span className="absolute left-0 top-1/2 h-5 w-0.5 -translate-y-1/2 rounded-r-full bg-brand-500" />
            )}
            <Icon
              className={'h-[18px] w-[18px] shrink-0 ' + (active ? 'text-brand-300' : '')}
              strokeWidth={1.75}
              aria-hidden
            />
            {label}
            {to === '/kyc' && kycStatus !== 'verified' && (
              <span className="num ml-auto rounded-full bg-status-pending px-1.5 py-0.5 text-2xs font-bold text-white">
                {done}/{STEP_SEQUENCE.length}
              </span>
            )}
          </Link>
        );
      })}
    </nav>
  );

  const brand = (
    <div className="flex items-center gap-2.5 border-b border-white/[0.07] px-5 py-5">
      {/* Teal tile against the shared navy — the one visual difference from the banking app. */}
      <span className="grid h-9 w-9 place-items-center rounded-control bg-gradient-to-br from-teal-500 to-emerald-600 shadow-[0_4px_12px_-2px_rgb(13_148_136/0.4)]">
        <ShieldPlus className="h-[18px] w-[18px] text-white" strokeWidth={2} aria-hidden />
      </span>
      <span className="min-w-0">
        <span className="block truncate text-sm font-semibold tracking-tight text-white">
          FinSecure
        </span>
        <span className="block text-2xs uppercase tracking-wider text-slate-400">Insurance</span>
      </span>
    </div>
  );

  return (
    <div className="min-h-dvh bg-surface-sunken">
      <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col bg-gradient-to-b from-shell-900 to-shell-950 lg:flex">
        {brand}
        {nav}
        <div className="border-t border-white/[0.07] p-3">
          <button
            type="button"
            onClick={() => {
              resetAll();
              window.location.href = '/login';
            }}
            className="focus-ring flex min-h-11 w-full items-center gap-3 rounded-control px-3 text-sm font-medium text-slate-400 transition-colors hover:bg-white/5 hover:text-white"
          >
            <RotateCcw className="h-[18px] w-[18px]" strokeWidth={1.75} aria-hidden />
            Reset demo data
          </button>
        </div>
      </aside>

      {drawerOpen && (
        <div className="fixed inset-0 z-40 lg:hidden">
          <button
            type="button"
            aria-label="Close navigation"
            onClick={() => setDrawerOpen(false)}
            className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm"
          />
          <div className="absolute inset-y-0 left-0 flex w-64 flex-col bg-gradient-to-b from-shell-900 to-shell-950 shadow-overlay">
            <div className="flex items-center justify-between border-b border-white/[0.07] pr-2">
              <div className="flex-1">{brand}</div>
              <button
                type="button"
                onClick={() => setDrawerOpen(false)}
                aria-label="Close navigation"
                className="focus-ring grid h-11 w-11 place-items-center rounded-control text-slate-300 hover:text-white"
              >
                <X className="h-5 w-5" aria-hidden />
              </button>
            </div>
            {nav}
          </div>
        </div>
      )}

      <div className="lg:pl-64">
        <header className="sticky top-0 z-30 border-b border-border-subtle bg-surface/80 backdrop-blur-xl">
          <div className="flex items-center gap-3 px-4 py-3 sm:px-6">
            <button
              type="button"
              onClick={() => setDrawerOpen(true)}
              aria-label="Open navigation"
              className="focus-ring grid h-11 w-11 place-items-center rounded-control text-slate-600 hover:bg-surface-sunken lg:hidden"
            >
              <Menu className="h-5 w-5" aria-hidden />
            </button>

            <span className="rounded-pill bg-status-pending-soft px-2.5 py-1 text-2xs font-bold uppercase tracking-wider text-status-pending ring-1 ring-inset ring-status-pending/15">
              Demo data
            </span>

            {/* Says out loud what makes this two apps and not one: the record is shared. */}
            <span className="hidden text-2xs text-slate-500 sm:block">
              KYC shared with FinSecure Bank
            </span>

            <div className="ml-auto flex items-center gap-1 sm:gap-2">
              <div className="flex items-center gap-2.5 rounded-control py-1 pl-1 pr-2">
                <span className="grid h-8 w-8 place-items-center rounded-full bg-teal-100 text-xs font-bold text-teal-800">
                  {initials(user?.name ?? '')}
                </span>
                <span className="hidden min-w-0 sm:block">
                  <span className="block truncate text-sm font-semibold text-slate-900">
                    {user?.name}
                  </span>
                  <span className="block text-2xs capitalize text-slate-500">{user?.role}</span>
                </span>
              </div>
              <button
                type="button"
                onClick={signOut}
                aria-label="Sign out"
                className="focus-ring grid h-11 w-11 place-items-center rounded-control text-slate-500 hover:bg-surface-sunken hover:text-status-rejected"
              >
                <LogOut className="h-[18px] w-[18px]" strokeWidth={1.75} aria-hidden />
              </button>
            </div>
          </div>
        </header>

        <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8">{children}</main>
      </div>
    </div>
  );
}

function initials(name: string): string {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return '—';
  return (parts[0]![0]! + (parts[1]?.[0] ?? '')).toUpperCase();
}
